/**
 * 新增
 */

import getHRDeptAddAction from '../request-functions/getHRDeptAddAction.js';

export default function HRDeptAddAction(pk_dept, pk_org, formId) {
    let postData = {
        pk_dept: pk_dept,
        pk_org: pk_org
    };
    return getHRDeptAddAction(postData)
        .then((res) => {
            if (res.success && res.data) {
                // 清空右侧表单
                this.emptyRightData();

                // 右侧表单进入编辑状态
                this.baseBrowseState(true);

                // 新增页面
                this.state.newAddPageFlag = true;
                // 新增时 显示批准文号批准单位  非新增时不显示
                this.props.form.setFormItemsVisible(formId, {approvenum: true});
                this.props.form.setFormItemsVisible(formId, {approvedept: true});

                // 编码的可编辑性和值根据后台数据决定
                this.props.form.setAllFormValue({[formId]: res.data.formdata[formId]});
                // 设置编码的可编辑性
                this.props.form.setFormItemsDisabled(formId, {code: !res.data.isCodeEditable});
                // 设置编码的值   新增页面  取消功能用
                this.autoGeneratedCode = res.data.autoGeneratedCode;
                // 设置billNo  附件用
                this.billNo = res.data.autoGeneratedCode;
            }else{
                this.HRDeptQueryOneAction();
                // 返回浏览态
                this.baseBrowseState();
            }
        })
        .catch(reason => {
            this.HRDeptQueryOneAction();
            // 返回浏览态
            this.baseBrowseState();
        });
}
