/**
 * 岗位新增
 */

import {hrAjax as proFetch} from 'src/hrpub/common/utils/utils';
import AddCondition from "../../../public/functions/addCondition";

/**
 *
 * @param func_type  1:组织，2：部门，
 * @param pk_org
 * @param typePk
 * @returns {PromiseLike<T> | Promise<T>}
 * @constructor
 */
export default function PostAddAction(func_type, pk_org, typePk) {
    // 清空详情页数据
    this.emptyDetailPage();
    let postData = {
        func_type,
        pk_org,
        typePk
    };
    return proFetch({
        url: '/nccloud/hrjf/post/PostAddAction.do',
        body: postData,
    })
        .then((res) => {
            if (res.success) {
                if (res.data) {
                    // 设置详情页数据
                    if (res.data.formdata && res.data.formdata.om_post) {
                        let formdata = {
                            'om_post': {
                                rows: res.data.formdata.om_post.rows
                            }
                        };
                        this.props.form.setAllFormValue(formdata);
                        let rowValues = res.data.formdata.om_post.rows[0].values;
                        let queryCondition = {
                            pk_group:this.businessInfo.groupId,
                            pk_hrorg:this.state.queryActionPkorg,
                            pk_org: rowValues.pk_org.value
                        };
                        let meta = this.props.meta.getMeta();
                        AddCondition(meta["om_post"], {
                            ...queryCondition
                        }, 'pk_dept');
                        this.props.meta.setMeta(meta);
                    }

                    if (res.data.formdata && res.data.formdata.post_jq) {
                        let post_jq_data = {
                            'post_jq':{
                                rows:res.data.formdata.post_jq.rows
                            }
                        };
                        this.props.form.setAllFormValue(post_jq_data);
                    }
                    // 设置编码的可编辑性
                    this.props.form.setFormItemsDisabled('om_post', {postcode: !res.data.isCodeEditable});
                    // 设置编码的值   新增页面  取消功能用
                    this.autoGeneratedCode = res.data.autoGeneratedCode;
                }
                // 新增
                this.updateState({
                    isNewAddFlag: true,
                    isDetailEdit: true,
                    isShowDetail: true
                }, () => {
                    // 详情页进入编辑状态
                    this.setDetailPageStatus('edit');
                });
            }
        });
}
